<?php


function rithook_menu () {
    $items['home'] = array(
        'title' => 'Cozy product management',
        'page callback' => 'rithook_filter_page',
        'access arguments' => array('access content'),
    );
    return $items;
}     

function rithook_filter_page () {
    return theme('rithook_home_page', array('title' => 'Testing'));
}


/*
    Implements hook_theme();
*/
function rithook_theme($existing, $type, $theme, $path) {
    return array(
        'rithook_home_page' => array(
            'variables' => array('title' => NULL),
            'template' => 'homepage',
        ),
    );
} 


function rithook_form_alter(&$form, &$form_state, $form_id) {

	//dpm($form);
	// add css to multiple ode form
	if ($form_id == 'customers_node_form' || $form_id == 'suppliers_node_form' || $form_id == 'products_node_form') {
		$form['author']['#access'] = FALSE;
		$form['#attached']['css'] = array(
      			drupal_get_path('module', 'rithook') . '/css/node_form.css',
      	);
		global $user;
		//dpm($user);
		if (!user_has_role(4) && !user_has_role(3)) {
      		$form['options']['#access'] = FALSE;
      		$form['revision_information']['#access'] = FALSE;
			
		}


	}

	if ($form_id == 'customers_node_form') {

		$form['field_customer_code']['#access'] = FALSE;
		$form['field_customer_source']['#access'] = FALSE;

		//$form['field_customer_address']['und'][0]['add_more']['value'] = 'Add more address';

		$form['#attached']['js'] = array(
      			drupal_get_path('module', 'rithook') . '/js/customers_node_form.js',
      	);

 		drupal_add_css(drupal_get_path('module', 'rithook') . '/css/customers_node_form.css');

		// Add js to check rev if field have change
		if (arg(1) != 'add') {
	 		drupal_add_js(drupal_get_path('module', 'rithook') . '/js/customers_node_form_edit.js');
		}
      	
	}

	elseif($form_id == 'suppliers_node_form') {
		$form['field_supplier_code']['#access'] = FALSE;


		$form['#attached']['js'] = array(
      			drupal_get_path('module', 'rithook') . '/js/suppliers_node_form.js',
      	);

		// Add js to check rev if field have change
		if (arg(1) != 'add') {
	 		drupal_add_js(drupal_get_path('module', 'rithook') . '/js/suppliers_node_form_edit.js');
		}


	}
	elseif($form_id == 'products_node_form') {

		$form['field_product_supplier']['und']['#suffix'] .= '<div>
			<a class="various" data-fancybox-type="iframe" href="/node/add/suppliers">Add new supplier</a>
		</div>';
		$form['#attached']['js'] = array(
      			drupal_get_path('module', 'rithook') . '/js/products_node_form.js',
      	);

 	 	//drupal_add_css(drupal_get_path('module', 'rithook') . '/css/products_node_form.css');


	}
}

function rithook_node_submit($node, $form, &$form_state) {

	if ($node->type == 'suppliers' && $node->field_supplier_code != "") {
		$node->field_supplier_code['und'][0]['value'] = gen_node_code($node);
	}
	elseif ($node->type == 'customers' && $node->field_customer_code != "") {
		$node->field_customer_code['und'][0]['value'] = gen_node_code($node);
	}
	elseif ($node->type == 'products') {
		$run_num = substr($node->field_product_code['und'][0]['value'], 0, 4);
		if ($run_num == 'XXXX') {
			$node->field_product_code['und'][0]['value'] = gen_node_code($node);
		}
	}
}

function gen_node_code($node) {

	
	if ($node->type == 'suppliers') {
		$counter = db_query("SELECT count(nid) FROM {node} WHERE type='".$node->type."' ")->fetchField();
		$run_num = str_pad($counter+1, 4, '0', STR_PAD_LEFT);
		return 'SP-'.$run_num.date('m').date('Y');
	}
	elseif ($node->type == 'customers') {
		$counter = db_query("SELECT count(nid) FROM {node} WHERE type='".$node->type."' ")->fetchField();
		$run_num = str_pad($counter+1, 4, '0', STR_PAD_LEFT);
		return 'CUST-'.$run_num.date('m').date('Y');
	}
	elseif ($node->type == 'products') {
		$counter = db_query("SELECT count(nid) FROM {node} WHERE type='".$node->type."' ")->fetchField();
		$run_num = str_pad($counter+1, 4, '0', STR_PAD_LEFT);
		return $run_num.substr($node->field_product_code['und'][0]['value'], 4);

	}

}